version: "2"
services:
  app:
    container_name: afs
    restart: always
    build: .
    ports:
      - "8830:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./dataDB:/data/db
    ports:
      - "8817:27017"